blank_issues_enabled: false
contact_links:
#  - name: Discourse forum for vaultwarden
#    url: https://vaultwarden.discourse.group/
#    about: Use this forum to request features or get help with usage/configuration.
  - name: Securenza Support
    url: https://securenza.be/support
    about: Create a support ticket for getting help with Vault.
